apiVersion: v1
kind: Pod
metadata: 
  name: cm-test-app
spec:
  containers:
  - name: tomcat
    image: kubeguide/tomcat-app:v1
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: serverconf
      mountPath: /configfiles
  volumes:
  - name: serverconf
    configMap:
      name: tomcat-conf 
